### ISSUE TITLE
I keep seeing ImageView no longer exists. You should not use this PhotoViewAttacher any more. in the logs. Am I doing something wrong?

### ISSUE THREAD

**Issue by sreejithraman** [chrisbanes/PhotoView#334]
I have a view pager where I use PhotoView. I keep seeing this log: `ImageView no longer exists. You should not use this PhotoViewAttacher any more`. Do I need to be destroying the PhotoViewAttacher somehow when the view is destroyed?

**Comment by shixinzhang** [comment]
Have you try  it and create a new object with new ImageView ?

**Comment by sreejithraman** [comment]
What do you mean?

**Comment by Jawnnypoo** [comment]
Sounds like the PhotoViewAttacher is staying around longer than the actual ImageView is. Are you holding onto references to the PhotoViewAttacher elsewhere? Also, are you changing the contents of your ViewPager by changing the items within the adapter dynamically?

**Comment by sreejithraman** [comment]
@Jawnnypoo I am using PhotoView directly rather than using an attacher. And I am using it with Glide. I am setting the image in `instantiateItem()` so this would be the only place where the photoview is changed

**Comment by k3b** [comment]
There was a memory leak in PhotoView where local PhotoViewAttacher was not freed. this should be fixed with #373

**Comment by gweiss27** [comment]
Hi there!

I am still getting this issue and I am using version 1.3.1.

I am only using the PhotoViewAttacher in my pagerAdapter and yes I am changing the items (loading the image when the page turns) dynamically.  It seems to be working fine but I am getting a ton of these errors and cant figure out what the problem is or how to make them stop!  

Thanks in advance!
----
Sounds like the PhotoViewAttacher is staying around longer than the actual ImageView is. Are you holding onto references to the PhotoViewAttacher elsewhere? Also, are you changing the contents of your ViewPager by changing the items within the adapter dynamically?
